---
- name: Ensure PHP packages are installed.
  package:
    name: "{{ php_packages }}"
    state: "{{ php_packages_state }}"
    enablerepo: "{{ php_enablerepo | default(omit, true) }}"
  notify: restart webserver

- name: Enable PHP repo so we get upgrades
  yum_repository:
    name: "{{ item }}"
    enabled: yes
  with_items: "{{ php_enablerepo.split(',') }}"