---
- name: Ensure PHP packages are installed.
  package:
    name: "{{ php_packages }}"
    state: "{{ php_packages_state }}"
    enablerepo: "{{ php_enablerepo | default(omit, true) }}"
  notify: restart webserver

- name: Enable PHP repo so we get upgrades
  yum_repository:
    name: "{{ item }}"
    baseurl: "{{ remi_repo_url }}"
    gpgkey: "{{ remi_repo_gpg_key_url }}"
    enabled: yes
  with_items: "{{ php_eenablerepo.split(',') }}"